### PR TITLE
Search improve for accents language.

### PR DESCRIPTION
**Pull request by JohnCod3**
Hi, hjyue1.

This is a improve your searchbox for accents languages.

I hope you like it and it can be implemented.

Thanks.

### CODE REVIEW

**Comment by hjyue1** [comment]
@JohnCod3 Thank you very much. We can maintain it together

**Comment by JohnCod3** [comment]
> @JohnCod3 Thank you very much. We can maintain it together

Thank you for accepting my improvement. Of course I would like to help in maintaining this repository.

You could also update it in NPM.

Again, thank you very much.

**Comment by hjyue1** [comment]
@JohnCod3  Ok, I released version 1.3.8 at NPM

**Comment by JohnCod3** [comment]
@hjyue1 Thank you very much.

**Pull request merged**
